{{- if not .Values.storage.data.existingClaim -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "planarally.fullname" . }}-data
  labels:
   {{- include "planarally.labels" . | nindent 4 }}
{{- if .Values.storage.data.annotations }}
  annotations:
{{ toYaml .Values.storage.data.annotations | indent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.storage.data.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.storage.data.size | quote }}
{{- if .Values.storage.data.storageClass }}
{{- if (eq "-" .Values.storage.data.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.storage.data.storageClass }}"
{{- end }}
{{- end }}
{{- end -}}